In [2]:
print("hello")

hello


In [11]:
# Dictionary
# key-value
# Faster search
# eg:google search key-keyword seach value-results
# eg:truecaller key-no value-name

contacts={8936184978:'Tom',7898452784:'Ann',9728563959:'Sara'}
for key,value in contacts.items():
    if key==7898452784:
        print(contacts[key])
    
    
        



Ann


In [15]:
num=10
if None: # (None,0,-1) None:it will not allow to get into loop
    print("Number is positive")

print("This will print always") # run by default

This will print always


In [16]:
num=10
if num==10:
    print("Number is positive")

print("This will print always")

Number is positive
This will print always


In [17]:
# Nested Loops

num=15
if (num>=10 and 20<=num):
    print("Number is positive")
elif(num>10 and 20>num):
    print("2nd division")
else:
    print("fail")

2nd division


In [18]:
num=15
if (num>10 or 10>num):
    if num>20:
        
        print("Number is positive")
    else:
        print("2nd division")

else:
    print("fail")

2nd division


In [19]:
a=70
b=34
c=89
if((a>=b) and(a>=c)):
    bigger=a
elif ((a>=a) and (b>=c)):
    bigger=b
else:
    bigger=c
print("Biggest no. is : {}".format(bigger))
    

Biggest no. is : 89


In [22]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [24]:
for i in range(1,10,2):  #range(start,stop,step),stop point always excluded
    print(i)

1
3
5
7
9


In [25]:
#for loop with else
x=[1,2,3,4]
for data in x:
    print(data)
else:
    print("no data available in x")

1
2
3
4
no data available in x


In [39]:
num=int(input())
prime=True
for i in range(2,int(num//2)+1):
    if num%i==0:
        prime=False
prime=True
print(prime)

 11


True


In [3]:
val1=20
val2=60
print("Write prime no.between {0} and {1}".format(val1,val2))

for num in range(val1, val2 + 1):
   if num > 1:
       for i in range(2, num):
           if (num % i) == 0:
               break
       else:
           print(num)

Write prime no.between 20 and 60
23
29
31
37
41
43
47
53
59


In [8]:
x=[1,2,3,4,5]
for num in x:
    if num%2==0:
        #print(num)
        continue
    print(num)
else:
    print('list data is over')

1
2
3
4
5
list data is over


In [25]:
x=[1,2,3,4,5,6,7,8,9,10]
val=11
found=False
for num in x:
    if num == val:
        print(f"Found {val} in the list!")
        found = True
        break 

if not found:
    print(f"{val} not found in the list.")

11 not found in the list.


In [18]:
x=["banana","apple","kiwi","strawberry"]
for fruit in x:
    if fruit == "strawberry":
        break
    else:
        print(fruit)
else:
    print('data is over')

strawberry


In [27]:
lst=['one','two','three','four']
lst.append('five') #append used to add at last
lst.insert(2,'six') #at specific pos
lst1=['seven','eight']
lst.extend(lst1) #add a list and combined to first
print(lst)

['one', 'two', 'six', 'three', 'four', 'five', 'seven', 'eight']


In [29]:
# Overridden

lst=[1,2,3,4,5]
lst1=[]
lst1=lst
lst1.append(4)
lst1.append(3)
print(lst)
print(lst1)



[1, 2, 3, 4, 5, 4, 3]
[1, 2, 3, 4, 5, 4, 3]


In [30]:
# split
#lst.count() frequency

lst="i,am learning ,python"
lst2=lst.split(",")
print(lst2)
print(lst)
print(type(lst))
print(type(lst2))

['i', 'am learning ', 'python']
i,am learning ,python
<class 'str'>
<class 'list'>


In [33]:
lst=[1,4,6,4,8,3]
print(lst[1]) #left to right
print(lst[-4]) #right to left

4
6


In [34]:
lst=[10,40,60,49]
lst1=["ajay","rajesh","julfi"]
lst2=lst+lst1  #extend using  +
print(lst2)

[10, 40, 60, 49, 'ajay', 'rajesh', 'julfi']


In [35]:
#lsit comprehension :provides a concise way to create list
power=[x**2 for x in range(10)]
print(power)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [37]:

lst2=[(i,i**2) for i in range(10)]
print(lst2)



[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81)]


In [30]:
matrix=[
    [1,2,3,4],
    [6,8,3,4],
    [7,8,9,3]
]
transposed=[]

n = len(matrix)
for i in range(n):
    for j in range(i + 1, n):
        matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]
print(matrix)

[[1, 6, 7, 4], [2, 8, 8, 4], [3, 3, 9, 3]]


In [34]:
# assignment 1
# matrix transpose using with and without function

#with function
import numpy as np
matrix=[
    [1,2,3,4],
    [6,8,3,4],
    [7,8,9,3]
]
transposed=np.transpose(matrix)
print(transposed)

[[1 6 7]
 [2 8 8]
 [3 3 9]
 [4 4 3]]


In [44]:
#Tuple

# can write list in tuple -nested tuple or hybrid

#nested tuple
lst=(1,(2,3,8),['hi',9.8])
print(type(lst))
print(lst)
print(lst[1])
print(lst[1][1])
lst[-1][1]

<class 'tuple'>
(1, (2, 3, 8), ['hi', 9.8])
(2, 3, 8)
3


9.8

In [47]:
lst=("hi",) #pass comma if passing only one value else it used as string
print(type(lst))

<class 'tuple'>


In [49]:
lst=('hi',[1,'hello'],3.5,'hello')
print(lst[1])
print(lst[1][0])
print(type(lst))

[1, 'hello']
1
<class 'tuple'>


In [52]:
lst=('hi',[1,'hello'],3.5,'hello')
lst[1][1]='bye' #changing value in tuple
print(lst[1][1])
print(lst)

bye
('hi', [1, 'bye'], 3.5, 'hello')


In [53]:
lst='prwatech' #string also immutable
lst[6]='j'

TypeError: 'str' object does not support item assignment

In [61]:
#tuple deletion
lst=(1,2,3,4,5,6)
#del lst[3]  #element deletion not possible in tuple
del lst#deleting full tuple is possible

In [57]:
#repeat element in tuple using * operator

lst=(('prwatech',)*5)
print(lst)
print(len(lst))

('prwatech', 'prwatech', 'prwatech', 'prwatech', 'prwatech')
5


In [62]:
#tuple indexing
#index () gives the index of elements
lst=(1,2,3,1,8,3,9,0,3,2,3)
print(lst.index(0))  # gives the index of 0


7


In [63]:
lst=(1,2,3,1,8,3,9,0,3,2,3)
print(lst.count(3)) # gives the frequency of 3

4


In [ ]:
#tuple membership
#in and not  in operator use to check elemen membership in tuple

lst=(1,2,3,1,8,3,9,0,3,2,3)
1 in lst

In [ ]:
#tuple length
lst=(1,2,3,1,8,3,9,0,3,2,3)
print(len(lst))

In [64]:
lst=(1,2,3,1,8,3,9,0,3,2,3)
print(sorted(lst))
lst2=sorted(lst,reverse=True)
print(lst2)

[0, 1, 1, 2, 2, 3, 3, 3, 3, 8, 9]
[9, 8, 3, 3, 3, 3, 2, 2, 1, 1, 0]


In [65]:
lst=(1,2,3,1,8,3,9,0,3,2,3)
print(min(lst)) #minimum element in tuple
print(max(lst))
print(sum(lst))


0
9


In [69]:
import statistics as lst
lst.mean((1,2,3,4,5))
lst.median((1,2,3,4,5))

3

In [70]:
import math as lst
lst.factorial(4)

24

In [ ]:
# Sets
# its immutable we can add & remove data
# sets can be use to perform mathematical operation like union,intersection,symmetric difference etc.
#doesnt hold duplicate records
#doesnt support indexing

In [76]:
lst=[1,2,3,4,5]
lst2=[]
lst2=lst #shares the addresses not values assigned

print(lst2)
print(id(lst))
print(id(lst2))



[1, 2, 3, 4, 5]
2196963505728
2196963505728


In [ ]:
# Assignment share elements without sharing address

lst=[1,2,3,4,5]
lst2=[]


In [77]:
#add value in set
lst={1,2,5,3}
lst.add(6) #it is unordered
lst
lst.update([7,10,3])
print(lst)


{1, 2, 3, 5, 6, 7, 10}


In [80]:
lst={1,2,5,3}
lst.update([11,12,0],(15,8))
print(lst)

{0, 1, 2, 3, 5, 8, 11, 12, 15}


In [89]:
#remove an element
lst={1,2,5,3}
#lst.remove(9) #shows error if item not found
lst.discard(6) #discard will not show error if o element found it uses exception
print(lst)

{1, 2, 3, 5}


In [91]:
#pop() means temporary deletion
lst={1,2,3,4,5,6,7,89,10,24,19}
a=lst.pop()
print(a)
print(lst)
b=lst.pop()
print(b)
print(lst)

1
{2, 3, 4, 5, 6, 7, 10, 19, 24, 89}
2
{3, 4, 5, 6, 7, 10, 19, 24, 89}


In [92]:
lst={1,2,3,4,5,6,7,89,10,24,19}
lst.clear() # it will remove all data  from set
print(lst)

set()


In [ ]:
# Assignment 3-how to reassign the data that is temporarily deleted


In [95]:
lst={1,2,3,4,5,6,9}
lst2={6,7,8,9,0}
print(lst | lst2) #either | or union function
print(lst.union(lst2))

print(lst&lst2) #either intersection function or &,it will give common elements from both
print(lst.intersection(lst2))

print(lst-lst2)#either difference function or ,it will give common elements from both
print(lst.difference(lst2))

print(lst ^ lst2)
print(lst.symmetric_difference(lst2))#either intersection function or &,it will give not common elements from both

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
{9, 6}
{9, 6}
{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5}
{0, 1, 2, 3, 4, 5, 7, 8}
{0, 1, 2, 3, 4, 5, 7, 8}


In [96]:
# issubset() lst1.issubset(lst2) check lst2 is subset of lst1
# issuperset() lst1.issuperset(lst2) check lst1 is superset of lst2
# frozenset() can't add value and indexing

lst1=frozenset([0,1,2,3])
lst2=frozenset([0,1,2,7,8])
print(lst2)
# lst1.add(5) #cant add value
# lst1[3] #dont support indexing




frozenset({0, 1, 2, 7, 8})


AttributeError: 'frozenset' object has no attribute 'add'

In [1]:
#Dictionary
#key-value pair
#key cannot be duplicated ,but values can be duplicated
my_dict={}
print(type(my_dict))

<class 'dict'>


In [2]:

my_dict={1:'a',2:'c',2:'b'}#overrite the value of key 2
print(my_dict)



{1: 'a', 2: 'b'}


In [7]:
co_vid={1:'rajiv',2:'shyam'}
print(co_vid[1])  #if using index it gives error when nothing found
print(co_vid.get(1)) #using .get() method it handle exception iskey not found
print(co_vid.get(4)) #gives None because no key found

rajiv
rajiv
None


In [12]:
#add or modify element
co_vid={1:'rajiv',2:'shyam'}
co_vid[3]='sam' #add new pair
print(co_vid)

#print(co_vid.pop(3)) #delete specific key mentioned
print(co_vid)
a=co_vid.popitem() #delete last key based on LIFO ,temporary since its pop
print(a) 
print(co_vid)

{1: 'rajiv', 2: 'shyam', 3: 'sam'}
{1: 'rajiv', 2: 'shyam', 3: 'sam'}
(3, 'sam')
{1: 'rajiv', 2: 'shyam'}


In [13]:
#delete
squ={2:4,3:9,4:16,5:25}
print(squ)
del squ[5] #deleting by key
print(squ)

{2: 4, 3: 9, 4: 16, 5: 25}
{2: 4, 3: 9, 4: 16}


In [14]:
squ={2:4,3:9,4:16,5:25}
squ.clear() #deletes all elements
print(squ)

{}


In [16]:
squ={2:4,3:9,4:16,5:25}
del squ

In [18]:
#copy doesnt share same address, copy values only
co_vid={1:'rajiv',2:'shyam'}
co_vaxine=co_vid.copy()
print(co_vaxine)
print(co_vid)
print(type(co_vaxine))
print(type(co_vid))
print(id(co_vaxine))
print(id(co_vid))

{1: 'rajiv', 2: 'shyam'}
{1: 'rajiv', 2: 'shyam'}
<class 'dict'>
<class 'dict'>
2874973840896
2874973840640


In [20]:
#dict.fromkeys

sub=dict.fromkeys(['math','English','hindi'],'0')  #maths,english,hindi are keys with same value 0
print(sub)

{'math': '0', 'English': '0', 'hindi': '0'}


In [23]:
squ={2:4,3:9,4:16,5:25}
print(squ)
print(squ.items())
print(squ.keys())
print(squ.values())
lst={}
print(dir(lst)) #list all operations related to dictionary

{2: 4, 3: 9, 4: 16, 5: 25}
dict_items([(2, 4), (3, 9), (4, 16), (5, 25)])
dict_keys([2, 3, 4, 5])
dict_values([4, 9, 16, 25])
['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']


In [25]:
squ={2:4,3:9,4:16,5:25}
d_sq={k:v for k,v in squ.items() if v>9}
print(d_sq)

{4: 16, 5: 25}


In [26]:
squ={2:4,3:9,4:16,5:25}

d_squ={k+5:v+2 for k,v in squ.items() if v>4}
print(d_squ)

{8: 11, 9: 18, 10: 27}


In [1]:
#Assignment-1-Transpose of a matrix with and without using  built-in function

#with function
import numpy as np
matrix=[
    [1,2,3,4],
    [6,8,3,4],
    [7,8,9,3]
]
transposed=np.transpose(matrix)
print(transposed)

[[1 6 7]
 [2 8 8]
 [3 3 9]
 [4 4 3]]


In [4]:
#without function
matrix=[
    [1,2,3,4],
    [6,8,3,4],
    [7,8,9,3]
]
transposed=[[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]
print(transposed)

[[1, 6, 7], [2, 8, 8], [3, 3, 9], [4, 4, 3]]


In [5]:
#Assignment 2-Share elements without sharing the address
lst=[1,2,3,4,5]
lst2=[]
lst2=lst.copy()
print(lst2)
print(id(lst))
print(id(lst2))

[1, 2, 3, 4, 5]
2115687303872
2115689658368


In [6]:
#Assignment 3-How to reassign the data that is temporarily

lst={1,2,3,4,5,6,7,89,10,24,19}
a=lst.pop()
print(a)
print(lst)
lst.add(a)
print(lst)

1
{2, 3, 4, 5, 6, 7, 10, 19, 24, 89}
{1, 2, 3, 4, 5, 6, 7, 10, 19, 24, 89}
